2023-03-28 15:36:21,814 - util.py[DEBUG]: Cloud-init v. 22.4.2-0ubuntu0~22.04.1 running 'init-local' at Tue, 28 Mar 2023 15:36:21 +0000. Up 15.69 seconds.
2023-03-28 15:36:21,815 - main.py[DEBUG]: No kernel command line url found.
2023-03-28 15:36:21,815 - main.py[DEBUG]: Closing stdin.
2023-03-28 15:36:21,830 - util.py[DEBUG]: Writing to /var/log/cloud-init.log - ab: [644] 0 bytes
2023-03-28 15:36:21,831 - util.py[DEBUG]: Changing the ownership of /var/log/cloud-init.log to 107:4
2023-03-28 15:36:21,831 - util.py[DEBUG]: Writing to /var/lib/cloud/data/python-version - wb: [644] 4 bytes
2023-03-28 15:36:21,832 - util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance/boot-finished
2023-03-28 15:36:21,832 - handlers.py[DEBUG]: start: init-local/check-cache: attempting to read from cache [check]
2023-03-28 15:36:21,832 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/obj.pkl (quiet=False)
2023-03-28 15:36:21,832 - stages.py[DEBUG]: no cache found
2023-03-28 15:36:21,832 - handlers.py[DEBUG]: finish: init-local/check-cache: SUCCESS: no cache found
2023-03-28 15:36:21,832 - util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance
2023-03-28 15:36:21,841 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.ubuntu.Distro'>
2023-03-28 15:36:21,842 - __init__.py[DEBUG]: Looking for data source in: ['None'], via packages ['', 'cloudinit.sources'] that matches dependencies ['FILESYSTEM']
2023-03-28 15:36:21,843 - __init__.py[DEBUG]: Searching for local data source in: []
2023-03-28 15:36:21,843 - main.py[DEBUG]: No local datasource found
2023-03-28 15:36:21,844 - util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)
2023-03-28 15:36:21,844 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/lo/address
2023-03-28 15:36:21,844 - util.py[DEBUG]: Reading from /sys/class/net/ens160/address (quiet=False)
2023-03-28 15:36:21,845 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/ens160/address
2023-03-28 15:36:21,845 - stages.py[DEBUG]: network config disabled by system_cfg
2023-03-28 15:36:21,845 - stages.py[INFO]: network config is disabled by system_cfg
2023-03-28 15:36:21,845 - main.py[DEBUG]: [local] Exiting without datasource
2023-03-28 15:36:21,846 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/status.json (via temporary file /var/lib/cloud/data/tmpu2_lyt7j) - w: [644] 474 bytes/chars
2023-03-28 15:36:21,846 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2023-03-28 15:36:21,846 - util.py[DEBUG]: Read 11 bytes from /proc/uptime
2023-03-28 15:36:21,846 - util.py[DEBUG]: cloud-init mode 'init' took 0.166 seconds (0.17)
2023-03-28 15:36:21,846 - handlers.py[DEBUG]: finish: init-local: SUCCESS: searching for local datasources
2023-03-28 15:38:06,751 - util.py[DEBUG]: Cloud-init v. 22.4.2-0ubuntu0~22.04.1 running 'init' at Tue, 28 Mar 2023 15:38:06 +0000. Up 120.65 seconds.
2023-03-28 15:38:06,751 - main.py[DEBUG]: No kernel command line url found.
2023-03-28 15:38:06,752 - main.py[DEBUG]: Closing stdin.
2023-03-28 15:38:06,758 - util.py[DEBUG]: Writing to /var/log/cloud-init.log - ab: [644] 0 bytes
2023-03-28 15:38:06,759 - util.py[DEBUG]: Changing the ownership of /var/log/cloud-init.log to 107:4
2023-03-28 15:38:06,759 - subp.py[DEBUG]: Running command ['ip', '--json', 'addr'] with allowed return codes [0] (shell=False, capture=True)
2023-03-28 15:38:06,855 - subp.py[DEBUG]: Running command ['ip', '-o', 'route', 'list'] with allowed return codes [0] (shell=False, capture=True)
2023-03-28 15:38:06,859 - subp.py[DEBUG]: Running command ['ip', '--oneline', '-6', 'route', 'list', 'table', 'all'] with allowed return codes [0, 1] (shell=False, capture=True)
2023-03-28 15:38:06,864 - handlers.py[DEBUG]: start: init-network/check-cache: attempting to read from cache [trust]
2023-03-28 15:38:06,864 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/obj.pkl (quiet=False)
2023-03-28 15:38:06,864 - stages.py[DEBUG]: no cache found
2023-03-28 15:38:06,864 - handlers.py[DEBUG]: finish: init-network/check-cache: SUCCESS: no cache found
2023-03-28 15:38:06,864 - util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance
2023-03-28 15:38:06,871 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.ubuntu.Distro'>
2023-03-28 15:38:06,871 - __init__.py[DEBUG]: Looking for data source in: ['None'], via packages ['', 'cloudinit.sources'] that matches dependencies ['FILESYSTEM', 'NETWORK']
2023-03-28 15:38:06,872 - __init__.py[DEBUG]: Searching for network data source in: ['DataSourceNone']
2023-03-28 15:38:06,872 - handlers.py[DEBUG]: start: init-network/search-None: searching for network data from DataSourceNone
2023-03-28 15:38:06,872 - __init__.py[DEBUG]: Seeing if we can get any data from <class 'cloudinit.sources.DataSourceNone.DataSourceNone'>
2023-03-28 15:38:06,872 - __init__.py[DEBUG]: Update datasource metadata and network config due to events: boot-new-instance
2023-03-28 15:38:06,872 - util.py[DEBUG]: Reading from /etc/hosts (quiet=False)
2023-03-28 15:38:06,873 - util.py[DEBUG]: Read 225 bytes from /etc/hosts
2023-03-28 15:38:06,878 - util.py[DEBUG]: Writing to /run/cloud-init/cloud-id-none - wb: [644] 5 bytes
2023-03-28 15:38:06,878 - util.py[DEBUG]: Creating symbolic link from '/run/cloud-init/cloud-id' => '/run/cloud-init/cloud-id-none'
2023-03-28 15:38:06,879 - atomic_helper.py[DEBUG]: Atomically writing to file /run/cloud-init/instance-data-sensitive.json (via temporary file /run/cloud-init/tmpd4bgys8v) - w: [600] 5354 bytes/chars
2023-03-28 15:38:06,879 - atomic_helper.py[DEBUG]: Atomically writing to file /run/cloud-init/instance-data.json (via temporary file /run/cloud-init/tmpzim243yj) - w: [644] 1412 bytes/chars
2023-03-28 15:38:06,879 - handlers.py[DEBUG]: finish: init-network/search-None: SUCCESS: found network data from DataSourceNone
2023-03-28 15:38:06,879 - stages.py[INFO]: Loaded datasource DataSourceNone - DataSourceNone
2023-03-28 15:38:06,880 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
2023-03-28 15:38:06,880 - util.py[DEBUG]: Read 3786 bytes from /etc/cloud/cloud.cfg
2023-03-28 15:38:06,880 - util.py[DEBUG]: Attempting to load yaml from string of length 3786 with allowed root types (<class 'dict'>,)
2023-03-28 15:38:06,908 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/subiquity-disable-cloudinit-networking.cfg (quiet=False)
2023-03-28 15:38:06,908 - util.py[DEBUG]: Read 28 bytes from /etc/cloud/cloud.cfg.d/subiquity-disable-cloudinit-networking.cfg
2023-03-28 15:38:06,909 - util.py[DEBUG]: Attempting to load yaml from string of length 28 with allowed root types (<class 'dict'>,)
2023-03-28 15:38:06,911 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/curtin-preserve-sources.cfg (quiet=False)
2023-03-28 15:38:06,911 - util.py[DEBUG]: Read 35 bytes from /etc/cloud/cloud.cfg.d/curtin-preserve-sources.cfg
2023-03-28 15:38:06,911 - util.py[DEBUG]: Attempting to load yaml from string of length 35 with allowed root types (<class 'dict'>,)
2023-03-28 15:38:06,912 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/99-installer.cfg (quiet=False)
2023-03-28 15:38:06,912 - util.py[DEBUG]: Read 554 bytes from /etc/cloud/cloud.cfg.d/99-installer.cfg
2023-03-28 15:38:06,912 - util.py[DEBUG]: Attempting to load yaml from string of length 554 with allowed root types (<class 'dict'>,)
2023-03-28 15:38:06,915 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/90_dpkg.cfg (quiet=False)
2023-03-28 15:38:06,915 - util.py[DEBUG]: Read 320 bytes from /etc/cloud/cloud.cfg.d/90_dpkg.cfg
2023-03-28 15:38:06,915 - util.py[DEBUG]: Attempting to load yaml from string of length 320 with allowed root types (<class 'dict'>,)
2023-03-28 15:38:06,919 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
2023-03-28 15:38:06,919 - util.py[DEBUG]: Read 2070 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
2023-03-28 15:38:06,919 - util.py[DEBUG]: Attempting to load yaml from string of length 2070 with allowed root types (<class 'dict'>,)
2023-03-28 15:38:06,927 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
2023-03-28 15:38:06,927 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2023-03-28 15:38:06,927 - util.py[DEBUG]: loaded blob returned None, returning default.
2023-03-28 15:38:06,928 - util.py[DEBUG]: Attempting to remove /var/lib/cloud/instance
2023-03-28 15:38:06,928 - util.py[DEBUG]: Creating symbolic link from '/var/lib/cloud/instance' => '/var/lib/cloud/instances/iid-datasource-none'
2023-03-28 15:38:06,932 - util.py[DEBUG]: Reading from /var/lib/cloud/instances/iid-datasource-none/datasource (quiet=False)
2023-03-28 15:38:06,932 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-datasource-none/datasource - wb: [644] 31 bytes
2023-03-28 15:38:06,932 - util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-datasource - wb: [644] 31 bytes
2023-03-28 15:38:06,933 - util.py[DEBUG]: Reading from /var/lib/cloud/data/instance-id (quiet=False)
2023-03-28 15:38:06,933 - stages.py[DEBUG]: previous iid found to be NO_PREVIOUS_INSTANCE_ID
2023-03-28 15:38:06,933 - util.py[DEBUG]: Writing to /var/lib/cloud/data/instance-id - wb: [644] 20 bytes
2023-03-28 15:38:06,933 - util.py[DEBUG]: Writing to /run/cloud-init/.instance-id - wb: [644] 20 bytes
2023-03-28 15:38:06,934 - util.py[DEBUG]: Writing to /var/lib/cloud/data/previous-instance-id - wb: [644] 24 bytes
2023-03-28 15:38:06,935 - util.py[DEBUG]: Writing to /var/lib/cloud/instance/obj.pkl - wb: [400] 6115 bytes
2023-03-28 15:38:06,935 - main.py[DEBUG]: [net] init will now be targeting instance id: iid-datasource-none. new=True
2023-03-28 15:38:06,935 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
2023-03-28 15:38:06,935 - util.py[DEBUG]: Read 3786 bytes from /etc/cloud/cloud.cfg
2023-03-28 15:38:06,935 - util.py[DEBUG]: Attempting to load yaml from string of length 3786 with allowed root types (<class 'dict'>,)
2023-03-28 15:38:06,948 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/subiquity-disable-cloudinit-networking.cfg (quiet=False)
2023-03-28 15:38:06,948 - util.py[DEBUG]: Read 28 bytes from /etc/cloud/cloud.cfg.d/subiquity-disable-cloudinit-networking.cfg
2023-03-28 15:38:06,948 - util.py[DEBUG]: Attempting to load yaml from string of length 28 with allowed root types (<class 'dict'>,)
2023-03-28 15:38:06,949 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/curtin-preserve-sources.cfg (quiet=False)
2023-03-28 15:38:06,949 - util.py[DEBUG]: Read 35 bytes from /etc/cloud/cloud.cfg.d/curtin-preserve-sources.cfg
2023-03-28 15:38:06,949 - util.py[DEBUG]: Attempting to load yaml from string of length 35 with allowed root types (<class 'dict'>,)
2023-03-28 15:38:06,949 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/99-installer.cfg (quiet=False)
2023-03-28 15:38:06,949 - util.py[DEBUG]: Read 554 bytes from /etc/cloud/cloud.cfg.d/99-installer.cfg
2023-03-28 15:38:06,949 - util.py[DEBUG]: Attempting to load yaml from string of length 554 with allowed root types (<class 'dict'>,)
2023-03-28 15:38:06,951 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/90_dpkg.cfg (quiet=False)
2023-03-28 15:38:06,951 - util.py[DEBUG]: Read 320 bytes from /etc/cloud/cloud.cfg.d/90_dpkg.cfg
2023-03-28 15:38:06,951 - util.py[DEBUG]: Attempting to load yaml from string of length 320 with allowed root types (<class 'dict'>,)
2023-03-28 15:38:06,953 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
2023-03-28 15:38:06,953 - util.py[DEBUG]: Read 2070 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
2023-03-28 15:38:06,953 - util.py[DEBUG]: Attempting to load yaml from string of length 2070 with allowed root types (<class 'dict'>,)
2023-03-28 15:38:06,957 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
2023-03-28 15:38:06,957 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2023-03-28 15:38:06,957 - util.py[DEBUG]: loaded blob returned None, returning default.
2023-03-28 15:38:06,959 - util.py[DEBUG]: Reading from /sys/class/net/lo/address (quiet=False)
2023-03-28 15:38:06,959 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/lo/address
2023-03-28 15:38:06,959 - util.py[DEBUG]: Reading from /sys/class/net/ens160/address (quiet=False)
2023-03-28 15:38:06,959 - util.py[DEBUG]: Read 18 bytes from /sys/class/net/ens160/address
2023-03-28 15:38:06,959 - stages.py[DEBUG]: network config disabled by system_cfg
2023-03-28 15:38:06,959 - stages.py[INFO]: network config is disabled by system_cfg
2023-03-28 15:38:06,959 - handlers.py[DEBUG]: start: init-network/setup-datasource: setting up datasource
2023-03-28 15:38:06,960 - handlers.py[DEBUG]: finish: init-network/setup-datasource: SUCCESS: setting up datasource
2023-03-28 15:38:06,960 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-datasource-none/user-data.txt - wb: [600] 370 bytes
2023-03-28 15:38:06,961 - util.py[DEBUG]: Attempting to load yaml from string of length 370 with allowed root types (<class 'dict'>,)
2023-03-28 15:38:06,986 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-datasource-none/user-data.txt.i - wb: [600] 675 bytes
2023-03-28 15:38:06,986 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-datasource-none/vendor-data.txt - wb: [600] 0 bytes
2023-03-28 15:38:06,987 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-datasource-none/vendor-data.txt.i - wb: [600] 308 bytes
2023-03-28 15:38:06,987 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-datasource-none/vendor-data2.txt - wb: [600] 0 bytes
2023-03-28 15:38:06,988 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-datasource-none/vendor-data2.txt.i - wb: [600] 308 bytes
2023-03-28 15:38:06,989 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.ubuntu.Distro'>
2023-03-28 15:38:06,990 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-datasource-none/sem/consume_data - wb: [644] 21 bytes
2023-03-28 15:38:06,991 - helpers.py[DEBUG]: Running consume_data using lock (<FileLock using file '/var/lib/cloud/instances/iid-datasource-none/sem/consume_data'>)
2023-03-28 15:38:06,991 - handlers.py[DEBUG]: start: init-network/consume-user-data: reading and applying user-data
2023-03-28 15:38:06,991 - stages.py[DEBUG]: Added default handler for {'text/cloud-config-jsonp', 'text/cloud-config'} from CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']]
2023-03-28 15:38:06,992 - stages.py[DEBUG]: Added default handler for {'text/x-shellscript'} from ShellScriptPartHandler: [['text/x-shellscript']]
2023-03-28 15:38:06,992 - stages.py[DEBUG]: Added default handler for {'text/x-shellscript-per-boot'} from ShellScriptByFreqPartHandler: [['text/x-shellscript-per-boot']]
2023-03-28 15:38:06,992 - stages.py[DEBUG]: Added default handler for {'text/x-shellscript-per-instance'} from ShellScriptByFreqPartHandler: [['text/x-shellscript-per-instance']]
2023-03-28 15:38:06,992 - stages.py[DEBUG]: Added default handler for {'text/x-shellscript-per-once'} from ShellScriptByFreqPartHandler: [['text/x-shellscript-per-once']]
2023-03-28 15:38:06,992 - stages.py[DEBUG]: Added default handler for {'text/cloud-boothook'} from BootHookPartHandler: [['text/cloud-boothook']]
2023-03-28 15:38:06,992 - stages.py[DEBUG]: Added default handler for {'text/jinja2'} from JinjaTemplatePartHandler: [['text/jinja2']]
2023-03-28 15:38:06,992 - __init__.py[DEBUG]: Calling handler CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']] (__begin__, None, 3) with frequency once-per-instance
2023-03-28 15:38:06,992 - __init__.py[DEBUG]: Calling handler ShellScriptPartHandler: [['text/x-shellscript']] (__begin__, None, 2) with frequency once-per-instance
2023-03-28 15:38:06,992 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-boot']] (__begin__, None, 2) with frequency once-per-instance
2023-03-28 15:38:06,992 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-instance']] (__begin__, None, 2) with frequency once-per-instance
2023-03-28 15:38:06,993 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-once']] (__begin__, None, 2) with frequency once-per-instance
2023-03-28 15:38:06,993 - __init__.py[DEBUG]: Calling handler BootHookPartHandler: [['text/cloud-boothook']] (__begin__, None, 2) with frequency once-per-instance
2023-03-28 15:38:06,993 - __init__.py[DEBUG]: Calling handler JinjaTemplatePartHandler: [['text/jinja2']] (__begin__, None, 3) with frequency once-per-instance
2023-03-28 15:38:06,993 - __init__.py[DEBUG]: {'MIME-Version': '1.0', 'Content-Type': 'text/cloud-config', 'Content-Disposition': 'attachment; filename="part-001"'}
2023-03-28 15:38:06,993 - __init__.py[DEBUG]: Calling handler CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']] (text/cloud-config, part-001, 3) with frequency once-per-instance
2023-03-28 15:38:06,993 - util.py[DEBUG]: Attempting to load yaml from string of length 370 with allowed root types (<class 'dict'>,)
2023-03-28 15:38:06,996 - cloud_config.py[DEBUG]: Merging by applying [('dict', ['replace']), ('list', []), ('str', [])]
2023-03-28 15:38:06,996 - __init__.py[DEBUG]: Calling handler CloudConfigPartHandler: [['text/cloud-config', 'text/cloud-config-jsonp']] (__end__, None, 3) with frequency once-per-instance
2023-03-28 15:38:06,998 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-datasource-none/cloud-config.txt - wb: [600] 420 bytes
2023-03-28 15:38:06,999 - __init__.py[DEBUG]: Calling handler ShellScriptPartHandler: [['text/x-shellscript']] (__end__, None, 2) with frequency once-per-instance
2023-03-28 15:38:06,999 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-boot']] (__end__, None, 2) with frequency once-per-instance
2023-03-28 15:38:06,999 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-instance']] (__end__, None, 2) with frequency once-per-instance
2023-03-28 15:38:06,999 - __init__.py[DEBUG]: Calling handler ShellScriptByFreqPartHandler: [['text/x-shellscript-per-once']] (__end__, None, 2) with frequency once-per-instance
2023-03-28 15:38:06,999 - __init__.py[DEBUG]: Calling handler BootHookPartHandler: [['text/cloud-boothook']] (__end__, None, 2) with frequency once-per-instance
2023-03-28 15:38:06,999 - __init__.py[DEBUG]: Calling handler JinjaTemplatePartHandler: [['text/jinja2']] (__end__, None, 3) with frequency once-per-instance
2023-03-28 15:38:06,999 - handlers.py[DEBUG]: finish: init-network/consume-user-data: SUCCESS: reading and applying user-data
2023-03-28 15:38:07,000 - handlers.py[DEBUG]: start: init-network/consume-vendor-data: reading and applying vendor-data
2023-03-28 15:38:07,000 - stages.py[DEBUG]: no vendordata from datasource
2023-03-28 15:38:07,000 - handlers.py[DEBUG]: finish: init-network/consume-vendor-data: SUCCESS: reading and applying vendor-data
2023-03-28 15:38:07,000 - handlers.py[DEBUG]: start: init-network/consume-vendor-data2: reading and applying vendor-data2
2023-03-28 15:38:07,000 - stages.py[DEBUG]: no vendordata2 from datasource
2023-03-28 15:38:07,000 - handlers.py[DEBUG]: finish: init-network/consume-vendor-data2: SUCCESS: reading and applying vendor-data2
2023-03-28 15:38:07,000 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg (quiet=False)
2023-03-28 15:38:07,000 - util.py[DEBUG]: Read 3786 bytes from /etc/cloud/cloud.cfg
2023-03-28 15:38:07,001 - util.py[DEBUG]: Attempting to load yaml from string of length 3786 with allowed root types (<class 'dict'>,)
2023-03-28 15:38:07,014 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/subiquity-disable-cloudinit-networking.cfg (quiet=False)
2023-03-28 15:38:07,014 - util.py[DEBUG]: Read 28 bytes from /etc/cloud/cloud.cfg.d/subiquity-disable-cloudinit-networking.cfg
2023-03-28 15:38:07,014 - util.py[DEBUG]: Attempting to load yaml from string of length 28 with allowed root types (<class 'dict'>,)
2023-03-28 15:38:07,014 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/curtin-preserve-sources.cfg (quiet=False)
2023-03-28 15:38:07,014 - util.py[DEBUG]: Read 35 bytes from /etc/cloud/cloud.cfg.d/curtin-preserve-sources.cfg
2023-03-28 15:38:07,014 - util.py[DEBUG]: Attempting to load yaml from string of length 35 with allowed root types (<class 'dict'>,)
2023-03-28 15:38:07,015 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/99-installer.cfg (quiet=False)
2023-03-28 15:38:07,015 - util.py[DEBUG]: Read 554 bytes from /etc/cloud/cloud.cfg.d/99-installer.cfg
2023-03-28 15:38:07,015 - util.py[DEBUG]: Attempting to load yaml from string of length 554 with allowed root types (<class 'dict'>,)
2023-03-28 15:38:07,016 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/90_dpkg.cfg (quiet=False)
2023-03-28 15:38:07,016 - util.py[DEBUG]: Read 320 bytes from /etc/cloud/cloud.cfg.d/90_dpkg.cfg
2023-03-28 15:38:07,016 - util.py[DEBUG]: Attempting to load yaml from string of length 320 with allowed root types (<class 'dict'>,)
2023-03-28 15:38:07,018 - util.py[DEBUG]: Reading from /etc/cloud/cloud.cfg.d/05_logging.cfg (quiet=False)
2023-03-28 15:38:07,019 - util.py[DEBUG]: Read 2070 bytes from /etc/cloud/cloud.cfg.d/05_logging.cfg
2023-03-28 15:38:07,019 - util.py[DEBUG]: Attempting to load yaml from string of length 2070 with allowed root types (<class 'dict'>,)
2023-03-28 15:38:07,023 - util.py[DEBUG]: Reading from /run/cloud-init/cloud.cfg (quiet=False)
2023-03-28 15:38:07,023 - util.py[DEBUG]: Attempting to load yaml from string of length 0 with allowed root types (<class 'dict'>,)
2023-03-28 15:38:07,023 - util.py[DEBUG]: loaded blob returned None, returning default.
2023-03-28 15:38:07,023 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/cloud-config.txt (quiet=False)
2023-03-28 15:38:07,023 - util.py[DEBUG]: Read 420 bytes from /var/lib/cloud/instance/cloud-config.txt
2023-03-28 15:38:07,023 - util.py[DEBUG]: Attempting to load yaml from string of length 420 with allowed root types (<class 'dict'>,)
2023-03-28 15:38:07,026 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-03-28 15:38:07,027 - util.py[DEBUG]: Read 133293 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-03-28 15:38:07,034 - util.py[DEBUG]: Reading from /var/lib/cloud/instance/cloud-config.txt (quiet=False)
2023-03-28 15:38:07,034 - util.py[DEBUG]: Read 420 bytes from /var/lib/cloud/instance/cloud-config.txt
2023-03-28 15:38:07,034 - util.py[DEBUG]: Attempting to load yaml from string of length 420 with allowed root types (<class 'dict'>,)
2023-03-28 15:38:07,039 - handlers.py[DEBUG]: start: init-network/activate-datasource: activating datasource
2023-03-28 15:38:07,039 - util.py[DEBUG]: Writing to /var/lib/cloud/instance/obj.pkl - wb: [400] 8521 bytes
2023-03-28 15:38:07,040 - handlers.py[DEBUG]: finish: init-network/activate-datasource: SUCCESS: activating datasource
2023-03-28 15:38:07,040 - main.py[DEBUG]: no di_report found in config.
2023-03-28 15:38:07,085 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-03-28 15:38:07,085 - util.py[DEBUG]: Read 133293 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-03-28 15:38:07,089 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-03-28 15:38:07,089 - util.py[DEBUG]: Read 133293 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-03-28 15:38:07,091 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-03-28 15:38:07,092 - util.py[DEBUG]: Read 133293 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-03-28 15:38:07,094 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-03-28 15:38:07,094 - util.py[DEBUG]: Read 133293 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-03-28 15:38:07,097 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-03-28 15:38:07,098 - util.py[DEBUG]: Read 133293 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-03-28 15:38:07,101 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-03-28 15:38:07,101 - util.py[DEBUG]: Read 133293 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-03-28 15:38:07,104 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-03-28 15:38:07,105 - util.py[DEBUG]: Read 133293 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-03-28 15:38:07,108 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-03-28 15:38:07,108 - util.py[DEBUG]: Read 133293 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-03-28 15:38:07,111 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-03-28 15:38:07,111 - util.py[DEBUG]: Read 133293 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-03-28 15:38:07,114 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-03-28 15:38:07,114 - util.py[DEBUG]: Read 133293 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-03-28 15:38:07,118 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-03-28 15:38:07,118 - util.py[DEBUG]: Read 133293 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-03-28 15:38:07,122 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-03-28 15:38:07,122 - util.py[DEBUG]: Read 133293 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-03-28 15:38:07,126 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-03-28 15:38:07,126 - util.py[DEBUG]: Read 133293 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-03-28 15:38:07,129 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-03-28 15:38:07,130 - util.py[DEBUG]: Read 133293 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-03-28 15:38:07,132 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.ubuntu.Distro'>
2023-03-28 15:38:07,134 - modules.py[INFO]: Skipping modules 'bootcmd,write-files,disk_setup,update_etc_hosts,ca-certs,rsyslog' because no applicable config is provided.
2023-03-28 15:38:07,134 - modules.py[DEBUG]: Running module migrator (<module 'cloudinit.config.cc_migrator' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_migrator.py'>) with frequency always
2023-03-28 15:38:07,134 - handlers.py[DEBUG]: start: init-network/config-migrator: running config-migrator with frequency always
2023-03-28 15:38:07,134 - helpers.py[DEBUG]: Running config-migrator using lock (<cloudinit.helpers.DummyLock object at 0x7f60d18e0550>)
2023-03-28 15:38:07,135 - cc_migrator.py[DEBUG]: Migrated 0 semaphore files to there canonicalized names
2023-03-28 15:38:07,135 - handlers.py[DEBUG]: finish: init-network/config-migrator: SUCCESS: config-migrator ran successfully
2023-03-28 15:38:07,135 - modules.py[DEBUG]: Running module seed_random (<module 'cloudinit.config.cc_seed_random' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_seed_random.py'>) with frequency once-per-instance
2023-03-28 15:38:07,135 - handlers.py[DEBUG]: start: init-network/config-seed_random: running config-seed_random with frequency once-per-instance
2023-03-28 15:38:07,135 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-datasource-none/sem/config_seed_random - wb: [644] 24 bytes
2023-03-28 15:38:07,136 - helpers.py[DEBUG]: Running config-seed_random using lock (<FileLock using file '/var/lib/cloud/instances/iid-datasource-none/sem/config_seed_random'>)
2023-03-28 15:38:07,136 - cc_seed_random.py[DEBUG]: no command provided
2023-03-28 15:38:07,136 - handlers.py[DEBUG]: finish: init-network/config-seed_random: SUCCESS: config-seed_random ran successfully
2023-03-28 15:38:07,136 - modules.py[DEBUG]: Running module growpart (<module 'cloudinit.config.cc_growpart' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_growpart.py'>) with frequency always
2023-03-28 15:38:07,136 - handlers.py[DEBUG]: start: init-network/config-growpart: running config-growpart with frequency always
2023-03-28 15:38:07,136 - helpers.py[DEBUG]: Running config-growpart using lock (<cloudinit.helpers.DummyLock object at 0x7f60d18e04f0>)
2023-03-28 15:38:07,136 - cc_growpart.py[DEBUG]: growpart disabled: mode=off
2023-03-28 15:38:07,137 - handlers.py[DEBUG]: finish: init-network/config-growpart: SUCCESS: config-growpart ran successfully
2023-03-28 15:38:07,137 - modules.py[DEBUG]: Running module resizefs (<module 'cloudinit.config.cc_resizefs' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_resizefs.py'>) with frequency always
2023-03-28 15:38:07,137 - handlers.py[DEBUG]: start: init-network/config-resizefs: running config-resizefs with frequency always
2023-03-28 15:38:07,137 - helpers.py[DEBUG]: Running config-resizefs using lock (<cloudinit.helpers.DummyLock object at 0x7f60d18e08b0>)
2023-03-28 15:38:07,137 - cc_resizefs.py[DEBUG]: Skipping module named resizefs, resizing disabled
2023-03-28 15:38:07,137 - handlers.py[DEBUG]: finish: init-network/config-resizefs: SUCCESS: config-resizefs ran successfully
2023-03-28 15:38:07,137 - modules.py[DEBUG]: Running module mounts (<module 'cloudinit.config.cc_mounts' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_mounts.py'>) with frequency once-per-instance
2023-03-28 15:38:07,137 - handlers.py[DEBUG]: start: init-network/config-mounts: running config-mounts with frequency once-per-instance
2023-03-28 15:38:07,138 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-datasource-none/sem/config_mounts - wb: [644] 23 bytes
2023-03-28 15:38:07,138 - helpers.py[DEBUG]: Running config-mounts using lock (<FileLock using file '/var/lib/cloud/instances/iid-datasource-none/sem/config_mounts'>)
2023-03-28 15:38:07,138 - cc_mounts.py[DEBUG]: mounts configuration is []
2023-03-28 15:38:07,138 - util.py[DEBUG]: Reading from /etc/fstab (quiet=False)
2023-03-28 15:38:07,138 - util.py[DEBUG]: Read 657 bytes from /etc/fstab
2023-03-28 15:38:07,139 - cc_mounts.py[DEBUG]: Attempting to determine the real name of ephemeral0
2023-03-28 15:38:07,139 - cc_mounts.py[DEBUG]: changed default device ephemeral0 => None
2023-03-28 15:38:07,139 - cc_mounts.py[DEBUG]: Ignoring nonexistent default named mount ephemeral0
2023-03-28 15:38:07,139 - cc_mounts.py[DEBUG]: Attempting to determine the real name of swap
2023-03-28 15:38:07,139 - cc_mounts.py[DEBUG]: changed default device swap => None
2023-03-28 15:38:07,139 - cc_mounts.py[DEBUG]: Ignoring nonexistent default named mount swap
2023-03-28 15:38:07,139 - cc_mounts.py[DEBUG]: no need to setup swap
2023-03-28 15:38:07,139 - cc_mounts.py[DEBUG]: No modifications to fstab needed
2023-03-28 15:38:07,139 - handlers.py[DEBUG]: finish: init-network/config-mounts: SUCCESS: config-mounts ran successfully
2023-03-28 15:38:07,139 - modules.py[DEBUG]: Running module set_hostname (<module 'cloudinit.config.cc_set_hostname' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_set_hostname.py'>) with frequency once-per-instance
2023-03-28 15:38:07,139 - handlers.py[DEBUG]: start: init-network/config-set_hostname: running config-set_hostname with frequency once-per-instance
2023-03-28 15:38:07,140 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-datasource-none/sem/config_set_hostname - wb: [644] 24 bytes
2023-03-28 15:38:07,140 - helpers.py[DEBUG]: Running config-set_hostname using lock (<FileLock using file '/var/lib/cloud/instances/iid-datasource-none/sem/config_set_hostname'>)
2023-03-28 15:38:07,140 - cc_set_hostname.py[DEBUG]: Configuration option 'preserve_hostname' is set, not setting the hostname in module set_hostname
2023-03-28 15:38:07,140 - handlers.py[DEBUG]: finish: init-network/config-set_hostname: SUCCESS: config-set_hostname ran successfully
2023-03-28 15:38:07,140 - modules.py[DEBUG]: Running module update_hostname (<module 'cloudinit.config.cc_update_hostname' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_update_hostname.py'>) with frequency always
2023-03-28 15:38:07,141 - handlers.py[DEBUG]: start: init-network/config-update_hostname: running config-update_hostname with frequency always
2023-03-28 15:38:07,141 - helpers.py[DEBUG]: Running config-update_hostname using lock (<cloudinit.helpers.DummyLock object at 0x7f60d18e04f0>)
2023-03-28 15:38:07,141 - cc_update_hostname.py[DEBUG]: Configuration option 'preserve_hostname' is set, not updating the hostname in module update_hostname
2023-03-28 15:38:07,141 - handlers.py[DEBUG]: finish: init-network/config-update_hostname: SUCCESS: config-update_hostname ran successfully
2023-03-28 15:38:07,141 - modules.py[DEBUG]: Running module users-groups (<module 'cloudinit.config.cc_users_groups' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_users_groups.py'>) with frequency once-per-instance
2023-03-28 15:38:07,141 - handlers.py[DEBUG]: start: init-network/config-users-groups: running config-users-groups with frequency once-per-instance
2023-03-28 15:38:07,141 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-datasource-none/sem/config_users_groups - wb: [644] 24 bytes
2023-03-28 15:38:07,142 - helpers.py[DEBUG]: Running config-users-groups using lock (<FileLock using file '/var/lib/cloud/instances/iid-datasource-none/sem/config_users_groups'>)
2023-03-28 15:38:07,144 - util.py[DEBUG]: Reading from /etc/os-release (quiet=True)
2023-03-28 15:38:07,144 - util.py[DEBUG]: Read 386 bytes from /etc/os-release
2023-03-28 15:38:07,144 - util.py[DEBUG]: Reading from /etc/system-image/channel.ini (quiet=True)
2023-03-28 15:38:07,144 - util.py[DEBUG]: Read 0 bytes from /etc/system-image/channel.ini
2023-03-28 15:38:07,145 - __init__.py[DEBUG]: Adding user administrator
2023-03-28 15:38:07,145 - subp.py[DEBUG]: Running hidden command to protect sensitive input/output logstring: ['useradd', 'administrator', '--comment', 'administrator', '--groups', 'adm,cdrom,dip,lxd,plugdev,sudo', '--password', 'REDACTED', '--shell', '/bin/bash', '-m']
2023-03-28 15:38:07,196 - handlers.py[DEBUG]: finish: init-network/config-users-groups: SUCCESS: config-users-groups ran successfully
2023-03-28 15:38:07,196 - modules.py[DEBUG]: Running module ssh (<module 'cloudinit.config.cc_ssh' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_ssh.py'>) with frequency once-per-instance
2023-03-28 15:38:07,196 - handlers.py[DEBUG]: start: init-network/config-ssh: running config-ssh with frequency once-per-instance
2023-03-28 15:38:07,196 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-datasource-none/sem/config_ssh - wb: [644] 24 bytes
2023-03-28 15:38:07,197 - helpers.py[DEBUG]: Running config-ssh using lock (<FileLock using file '/var/lib/cloud/instances/iid-datasource-none/sem/config_ssh'>)
2023-03-28 15:38:07,198 - subp.py[DEBUG]: Running command ['ssh-keygen', '-t', 'rsa', '-N', '', '-f', '/etc/ssh/ssh_host_rsa_key'] with allowed return codes [0] (shell=False, capture=True)
2023-03-28 15:38:08,693 - util.py[DEBUG]: Group ssh_keys is not a valid group name
2023-03-28 15:38:08,694 - subp.py[DEBUG]: Running command ['ssh-keygen', '-t', 'dsa', '-N', '', '-f', '/etc/ssh/ssh_host_dsa_key'] with allowed return codes [0] (shell=False, capture=True)
2023-03-28 15:38:08,824 - util.py[DEBUG]: Group ssh_keys is not a valid group name
2023-03-28 15:38:08,824 - subp.py[DEBUG]: Running command ['ssh-keygen', '-t', 'ecdsa', '-N', '', '-f', '/etc/ssh/ssh_host_ecdsa_key'] with allowed return codes [0] (shell=False, capture=True)
2023-03-28 15:38:08,854 - util.py[DEBUG]: Group ssh_keys is not a valid group name
2023-03-28 15:38:08,855 - subp.py[DEBUG]: Running command ['ssh-keygen', '-t', 'ed25519', '-N', '', '-f', '/etc/ssh/ssh_host_ed25519_key'] with allowed return codes [0] (shell=False, capture=True)
2023-03-28 15:38:08,863 - util.py[DEBUG]: Group ssh_keys is not a valid group name
2023-03-28 15:38:08,864 - util.py[DEBUG]: Reading from /etc/ssh/ssh_host_ed25519_key.pub (quiet=False)
2023-03-28 15:38:08,864 - util.py[DEBUG]: Read 97 bytes from /etc/ssh/ssh_host_ed25519_key.pub
2023-03-28 15:38:08,864 - util.py[DEBUG]: Reading from /etc/ssh/ssh_host_rsa_key.pub (quiet=False)
2023-03-28 15:38:08,864 - util.py[DEBUG]: Read 569 bytes from /etc/ssh/ssh_host_rsa_key.pub
2023-03-28 15:38:08,864 - util.py[DEBUG]: Reading from /etc/ssh/ssh_host_ecdsa_key.pub (quiet=False)
2023-03-28 15:38:08,864 - util.py[DEBUG]: Read 177 bytes from /etc/ssh/ssh_host_ecdsa_key.pub
2023-03-28 15:38:08,865 - util.py[DEBUG]: Reading from /etc/ssh/sshd_config (quiet=False)
2023-03-28 15:38:08,866 - util.py[DEBUG]: Read 3254 bytes from /etc/ssh/sshd_config
2023-03-28 15:38:08,867 - util.py[DEBUG]: Changing the ownership of /root/.ssh to 0:0
2023-03-28 15:38:08,867 - util.py[DEBUG]: Writing to /root/.ssh/authorized_keys - wb: [600] 0 bytes
2023-03-28 15:38:08,867 - util.py[DEBUG]: Changing the ownership of /root/.ssh/authorized_keys to 0:0
2023-03-28 15:38:08,868 - util.py[DEBUG]: Reading from /root/.ssh/authorized_keys (quiet=False)
2023-03-28 15:38:08,868 - util.py[DEBUG]: Read 0 bytes from /root/.ssh/authorized_keys
2023-03-28 15:38:08,868 - util.py[DEBUG]: Writing to /root/.ssh/authorized_keys - wb: [600] 0 bytes
2023-03-28 15:38:08,869 - handlers.py[DEBUG]: finish: init-network/config-ssh: SUCCESS: config-ssh ran successfully
2023-03-28 15:38:08,869 - main.py[DEBUG]: Ran 9 modules with 0 failures
2023-03-28 15:38:08,869 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/status.json (via temporary file /var/lib/cloud/data/tmpt5d1xlg1) - w: [644] 514 bytes/chars
2023-03-28 15:38:08,869 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2023-03-28 15:38:08,869 - util.py[DEBUG]: Read 14 bytes from /proc/uptime
2023-03-28 15:38:08,870 - util.py[DEBUG]: cloud-init mode 'init' took 2.187 seconds (2.19)
2023-03-28 15:38:08,870 - handlers.py[DEBUG]: finish: init-network: SUCCESS: searching for network datasources
2023-03-28 23:37:36,243 - util.py[DEBUG]: Cloud-init v. 22.4.2-0ubuntu0~22.04.1 running 'modules:config' at Tue, 28 Mar 2023 23:37:36 +0000. Up 138.94 seconds.
2023-03-28 23:37:36,250 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-03-28 23:37:36,251 - util.py[DEBUG]: Read 133293 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-03-28 23:37:36,257 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-03-28 23:37:36,257 - util.py[DEBUG]: Read 133293 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-03-28 23:37:36,264 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-03-28 23:37:36,264 - util.py[DEBUG]: Read 133293 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-03-28 23:37:36,272 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-03-28 23:37:36,272 - util.py[DEBUG]: Read 133293 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-03-28 23:37:36,280 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-03-28 23:37:36,280 - util.py[DEBUG]: Read 133293 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-03-28 23:37:36,286 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-03-28 23:37:36,287 - util.py[DEBUG]: Read 133293 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-03-28 23:37:36,291 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-03-28 23:37:36,292 - util.py[DEBUG]: Read 133293 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-03-28 23:37:36,297 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-03-28 23:37:36,298 - util.py[DEBUG]: Read 133293 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-03-28 23:37:36,303 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-03-28 23:37:36,304 - util.py[DEBUG]: Read 133293 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-03-28 23:37:36,315 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-03-28 23:37:36,315 - util.py[DEBUG]: Read 133293 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-03-28 23:37:36,326 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-03-28 23:37:36,326 - util.py[DEBUG]: Read 133293 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-03-28 23:37:36,333 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-03-28 23:37:36,333 - util.py[DEBUG]: Read 133293 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-03-28 23:37:36,343 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-03-28 23:37:36,343 - util.py[DEBUG]: Read 133293 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-03-28 23:37:36,348 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-03-28 23:37:36,348 - util.py[DEBUG]: Read 133293 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-03-28 23:37:36,354 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-03-28 23:37:36,355 - util.py[DEBUG]: Read 133293 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-03-28 23:37:36,360 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-03-28 23:37:36,360 - util.py[DEBUG]: Read 133293 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-03-28 23:37:36,361 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.ubuntu.Distro'>
2023-03-28 23:37:36,364 - modules.py[INFO]: Skipping modules 'wireguard,snap,ubuntu_autoinstall,keyboard,apt-pipelining,ubuntu-advantage,ntp,timezone,disable-ec2-metadata,runcmd' because no applicable config is provided.
2023-03-28 23:37:36,364 - modules.py[DEBUG]: Running module ssh-import-id (<module 'cloudinit.config.cc_ssh_import_id' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_ssh_import_id.py'>) with frequency once-per-instance
2023-03-28 23:37:36,364 - handlers.py[DEBUG]: start: modules-config/config-ssh-import-id: running config-ssh-import-id with frequency once-per-instance
2023-03-28 23:37:36,365 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-datasource-none/sem/config_ssh_import_id - wb: [644] 25 bytes
2023-03-28 23:37:36,365 - helpers.py[DEBUG]: Running config-ssh-import-id using lock (<FileLock using file '/var/lib/cloud/instances/iid-datasource-none/sem/config_ssh_import_id'>)
2023-03-28 23:37:36,365 - cc_ssh_import_id.py[DEBUG]: Skipping module named ssh-import-id, no 'ssh_import_id' directives found.
2023-03-28 23:37:36,365 - handlers.py[DEBUG]: finish: modules-config/config-ssh-import-id: SUCCESS: config-ssh-import-id ran successfully
2023-03-28 23:37:36,365 - modules.py[DEBUG]: Running module locale (<module 'cloudinit.config.cc_locale' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_locale.py'>) with frequency once-per-instance
2023-03-28 23:37:36,366 - handlers.py[DEBUG]: start: modules-config/config-locale: running config-locale with frequency once-per-instance
2023-03-28 23:37:36,368 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-datasource-none/sem/config_locale - wb: [644] 25 bytes
2023-03-28 23:37:36,370 - helpers.py[DEBUG]: Running config-locale using lock (<FileLock using file '/var/lib/cloud/instances/iid-datasource-none/sem/config_locale'>)
2023-03-28 23:37:36,370 - util.py[DEBUG]: Reading from /etc/default/locale (quiet=False)
2023-03-28 23:37:36,370 - util.py[DEBUG]: Read 13 bytes from /etc/default/locale
2023-03-28 23:37:36,370 - cc_locale.py[DEBUG]: Setting locale to en_US.UTF-8
2023-03-28 23:37:36,371 - debian.py[DEBUG]: Generating locales for en_US.UTF-8
2023-03-28 23:37:36,371 - subp.py[DEBUG]: Running command ['locale-gen', 'en_US.UTF-8'] with allowed return codes [0] (shell=False, capture=False)
2023-03-28 23:37:39,967 - debian.py[DEBUG]: Updating /etc/default/locale with locale setting LANG=en_US.UTF-8
2023-03-28 23:37:39,967 - subp.py[DEBUG]: Running command ['update-locale', '--locale-file=/etc/default/locale', 'LANG=en_US.UTF-8'] with allowed return codes [0] (shell=False, capture=False)
2023-03-28 23:37:40,037 - handlers.py[DEBUG]: finish: modules-config/config-locale: SUCCESS: config-locale ran successfully
2023-03-28 23:37:40,037 - modules.py[DEBUG]: Running module set-passwords (<module 'cloudinit.config.cc_set_passwords' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_set_passwords.py'>) with frequency once-per-instance
2023-03-28 23:37:40,037 - handlers.py[DEBUG]: start: modules-config/config-set-passwords: running config-set-passwords with frequency once-per-instance
2023-03-28 23:37:40,037 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-datasource-none/sem/config_set_passwords - wb: [644] 25 bytes
2023-03-28 23:37:40,038 - helpers.py[DEBUG]: Running config-set-passwords using lock (<FileLock using file '/var/lib/cloud/instances/iid-datasource-none/sem/config_set_passwords'>)
2023-03-28 23:37:40,038 - subp.py[DEBUG]: Running command ['systemctl', 'status', 'ssh'] with allowed return codes [0] (shell=False, capture=True)
2023-03-28 23:37:40,048 - util.py[DEBUG]: Writing to /etc/ssh/sshd_config.d/50-cloud-init.conf - ab: [600] 0 bytes
2023-03-28 23:37:40,049 - util.py[DEBUG]: Reading from /etc/ssh/sshd_config.d/50-cloud-init.conf (quiet=False)
2023-03-28 23:37:40,049 - util.py[DEBUG]: Read 0 bytes from /etc/ssh/sshd_config.d/50-cloud-init.conf
2023-03-28 23:37:40,049 - ssh_util.py[DEBUG]: line 1: option PasswordAuthentication added with yes
2023-03-28 23:37:40,049 - util.py[DEBUG]: Writing to /etc/ssh/sshd_config.d/50-cloud-init.conf - wb: [600] 27 bytes
2023-03-28 23:37:40,050 - subp.py[DEBUG]: Running command ['systemctl', 'restart', 'ssh'] with allowed return codes [0] (shell=False, capture=True)
2023-03-28 23:37:40,105 - cc_set_passwords.py[DEBUG]: Restarted the SSH daemon.
2023-03-28 23:37:40,105 - handlers.py[DEBUG]: finish: modules-config/config-set-passwords: SUCCESS: config-set-passwords ran successfully
2023-03-28 23:37:40,105 - modules.py[DEBUG]: Running module grub-dpkg (<module 'cloudinit.config.cc_grub_dpkg' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_grub_dpkg.py'>) with frequency once-per-instance
2023-03-28 23:37:40,106 - handlers.py[DEBUG]: start: modules-config/config-grub-dpkg: running config-grub-dpkg with frequency once-per-instance
2023-03-28 23:37:40,106 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-datasource-none/sem/config_grub_dpkg - wb: [644] 24 bytes
2023-03-28 23:37:40,106 - helpers.py[DEBUG]: Running config-grub-dpkg using lock (<FileLock using file '/var/lib/cloud/instances/iid-datasource-none/sem/config_grub_dpkg'>)
2023-03-28 23:37:40,106 - subp.py[DEBUG]: Running command ['grub-probe', '-t', 'disk', '/boot'] with allowed return codes [0] (shell=False, capture=True)
2023-03-28 23:37:40,152 - subp.py[DEBUG]: Running command ['udevadm', 'info', '--root', '--query=symlink', '/dev/sda'] with allowed return codes [0] (shell=False, capture=True)
2023-03-28 23:37:40,157 - cc_grub_dpkg.py[DEBUG]: considering these device symlinks: /dev/disk/by-path/pci-0000:00:10.0-scsi-0:0:0:0
2023-03-28 23:37:40,157 - cc_grub_dpkg.py[DEBUG]: filtered to these disk/by-id symlinks: 
2023-03-28 23:37:40,157 - cc_grub_dpkg.py[DEBUG]: selected /dev/sda
2023-03-28 23:37:40,157 - cc_grub_dpkg.py[DEBUG]: Setting grub debconf-set-selections with '/dev/sda','false'
2023-03-28 23:37:40,157 - subp.py[DEBUG]: Running command ['debconf-set-selections'] with allowed return codes [0] (shell=False, capture=True)
2023-03-28 23:37:40,503 - handlers.py[DEBUG]: finish: modules-config/config-grub-dpkg: SUCCESS: config-grub-dpkg ran successfully
2023-03-28 23:37:40,504 - modules.py[DEBUG]: Running module apt-configure (<module 'cloudinit.config.cc_apt_configure' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_apt_configure.py'>) with frequency once-per-instance
2023-03-28 23:37:40,504 - handlers.py[DEBUG]: start: modules-config/config-apt-configure: running config-apt-configure with frequency once-per-instance
2023-03-28 23:37:40,504 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-datasource-none/sem/config_apt_configure - wb: [644] 24 bytes
2023-03-28 23:37:40,505 - helpers.py[DEBUG]: Running config-apt-configure using lock (<FileLock using file '/var/lib/cloud/instances/iid-datasource-none/sem/config_apt_configure'>)
2023-03-28 23:37:40,505 - cc_apt_configure.py[DEBUG]: debconf_selections was not set in config
2023-03-28 23:37:40,505 - cc_apt_configure.py[DEBUG]: handling apt config: {'preserve_sources_list': True}
2023-03-28 23:37:40,505 - subp.py[DEBUG]: Running command ['lsb_release', '--all'] with allowed return codes [0] (shell=False, capture=True)
2023-03-28 23:37:40,560 - subp.py[DEBUG]: Running command ['dpkg', '--print-architecture'] with allowed return codes [0] (shell=False, capture=True)
2023-03-28 23:37:40,563 - cc_apt_configure.py[DEBUG]: got primary mirror: None
2023-03-28 23:37:40,563 - cc_apt_configure.py[DEBUG]: got security mirror: None
2023-03-28 23:37:40,563 - subp.py[DEBUG]: Running command ['dpkg', '--print-architecture'] with allowed return codes [0] (shell=False, capture=True)
2023-03-28 23:37:40,565 - util.py[DEBUG]: search for mirror in candidates: '[]'
2023-03-28 23:37:40,565 - util.py[DEBUG]: search for mirror in candidates: '[]'
2023-03-28 23:37:40,566 - __init__.py[DEBUG]: filtered distro mirror info: {'primary': 'http://archive.ubuntu.com/ubuntu', 'security': 'http://security.ubuntu.com/ubuntu'}
2023-03-28 23:37:40,566 - cc_apt_configure.py[DEBUG]: Apt Mirror info: {'primary': 'http://archive.ubuntu.com/ubuntu', 'security': 'http://security.ubuntu.com/ubuntu', 'PRIMARY': 'http://archive.ubuntu.com/ubuntu', 'SECURITY': 'http://security.ubuntu.com/ubuntu', 'MIRROR': 'http://archive.ubuntu.com/ubuntu'}
2023-03-28 23:37:40,566 - handlers.py[DEBUG]: finish: modules-config/config-apt-configure: SUCCESS: config-apt-configure ran successfully
2023-03-28 23:37:40,566 - modules.py[DEBUG]: Running module byobu (<module 'cloudinit.config.cc_byobu' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_byobu.py'>) with frequency once-per-instance
2023-03-28 23:37:40,566 - handlers.py[DEBUG]: start: modules-config/config-byobu: running config-byobu with frequency once-per-instance
2023-03-28 23:37:40,566 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-datasource-none/sem/config_byobu - wb: [644] 25 bytes
2023-03-28 23:37:40,567 - helpers.py[DEBUG]: Running config-byobu using lock (<FileLock using file '/var/lib/cloud/instances/iid-datasource-none/sem/config_byobu'>)
2023-03-28 23:37:40,567 - cc_byobu.py[DEBUG]: Skipping module named byobu, no 'byobu' values found
2023-03-28 23:37:40,567 - handlers.py[DEBUG]: finish: modules-config/config-byobu: SUCCESS: config-byobu ran successfully
2023-03-28 23:37:40,567 - main.py[DEBUG]: Ran 6 modules with 0 failures
2023-03-28 23:37:40,568 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/status.json (via temporary file /var/lib/cloud/data/tmpic8clrqu) - w: [644] 541 bytes/chars
2023-03-28 23:37:40,568 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2023-03-28 23:37:40,568 - util.py[DEBUG]: Read 14 bytes from /proc/uptime
2023-03-28 23:37:40,568 - util.py[DEBUG]: cloud-init mode 'modules' took 4.525 seconds (4.52)
2023-03-28 23:37:40,568 - handlers.py[DEBUG]: finish: modules-config: SUCCESS: running modules for config
2023-03-28 23:37:41,047 - util.py[DEBUG]: Cloud-init v. 22.4.2-0ubuntu0~22.04.1 running 'modules:final' at Tue, 28 Mar 2023 23:37:40 +0000. Up 143.81 seconds.
2023-03-28 23:37:41,051 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-03-28 23:37:41,052 - util.py[DEBUG]: Read 133293 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-03-28 23:37:41,055 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-03-28 23:37:41,056 - util.py[DEBUG]: Read 133293 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-03-28 23:37:41,059 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-03-28 23:37:41,059 - util.py[DEBUG]: Read 133293 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-03-28 23:37:41,062 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-03-28 23:37:41,062 - util.py[DEBUG]: Read 133293 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-03-28 23:37:41,068 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-03-28 23:37:41,069 - util.py[DEBUG]: Read 133293 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-03-28 23:37:41,071 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-03-28 23:37:41,072 - util.py[DEBUG]: Read 133293 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-03-28 23:37:41,075 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-03-28 23:37:41,075 - util.py[DEBUG]: Read 133293 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-03-28 23:37:41,079 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-03-28 23:37:41,079 - util.py[DEBUG]: Read 133293 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-03-28 23:37:41,082 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-03-28 23:37:41,082 - util.py[DEBUG]: Read 133293 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-03-28 23:37:41,087 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-03-28 23:37:41,087 - util.py[DEBUG]: Read 133293 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-03-28 23:37:41,091 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-03-28 23:37:41,091 - util.py[DEBUG]: Read 133293 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-03-28 23:37:41,096 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-03-28 23:37:41,096 - util.py[DEBUG]: Read 133293 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-03-28 23:37:41,098 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-03-28 23:37:41,099 - util.py[DEBUG]: Read 133293 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-03-28 23:37:41,100 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-03-28 23:37:41,101 - util.py[DEBUG]: Read 133293 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-03-28 23:37:41,103 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-03-28 23:37:41,103 - util.py[DEBUG]: Read 133293 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-03-28 23:37:41,107 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-03-28 23:37:41,107 - util.py[DEBUG]: Read 133293 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-03-28 23:37:41,109 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-03-28 23:37:41,109 - util.py[DEBUG]: Read 133293 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-03-28 23:37:41,111 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-03-28 23:37:41,112 - util.py[DEBUG]: Read 133293 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-03-28 23:37:41,114 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-03-28 23:37:41,115 - util.py[DEBUG]: Read 133293 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-03-28 23:37:41,117 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-03-28 23:37:41,117 - util.py[DEBUG]: Read 133293 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-03-28 23:37:41,120 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-03-28 23:37:41,120 - util.py[DEBUG]: Read 133293 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-03-28 23:37:41,122 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-03-28 23:37:41,123 - util.py[DEBUG]: Read 133293 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-03-28 23:37:41,125 - util.py[DEBUG]: Reading from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json (quiet=False)
2023-03-28 23:37:41,125 - util.py[DEBUG]: Read 133293 bytes from /usr/lib/python3/dist-packages/cloudinit/config/schemas/schema-cloud-config-v1.json
2023-03-28 23:37:41,127 - stages.py[DEBUG]: Using distro class <class 'cloudinit.distros.ubuntu.Distro'>
2023-03-28 23:37:41,130 - modules.py[INFO]: Skipping modules 'package-update-upgrade-install,fan,landscape,lxd,ubuntu-drivers,write-files-deferred,puppet,chef,ansible,mcollective,salt-minion,phone-home,power-state-change' because no applicable config is provided.
2023-03-28 23:37:41,130 - modules.py[DEBUG]: Running module reset_rmc (<module 'cloudinit.config.cc_reset_rmc' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_reset_rmc.py'>) with frequency once-per-instance
2023-03-28 23:37:41,131 - handlers.py[DEBUG]: start: modules-final/config-reset_rmc: running config-reset_rmc with frequency once-per-instance
2023-03-28 23:37:41,131 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-datasource-none/sem/config_reset_rmc - wb: [644] 25 bytes
2023-03-28 23:37:41,132 - helpers.py[DEBUG]: Running config-reset_rmc using lock (<FileLock using file '/var/lib/cloud/instances/iid-datasource-none/sem/config_reset_rmc'>)
2023-03-28 23:37:41,132 - cc_reset_rmc.py[DEBUG]: Skipping creation of new ct_node_id node
2023-03-28 23:37:41,132 - handlers.py[DEBUG]: finish: modules-final/config-reset_rmc: SUCCESS: config-reset_rmc ran successfully
2023-03-28 23:37:41,132 - modules.py[DEBUG]: Running module refresh_rmc_and_interface (<module 'cloudinit.config.cc_refresh_rmc_and_interface' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_refresh_rmc_and_interface.py'>) with frequency always
2023-03-28 23:37:41,132 - handlers.py[DEBUG]: start: modules-final/config-refresh_rmc_and_interface: running config-refresh_rmc_and_interface with frequency always
2023-03-28 23:37:41,132 - helpers.py[DEBUG]: Running config-refresh_rmc_and_interface using lock (<cloudinit.helpers.DummyLock object at 0x7fe94a161330>)
2023-03-28 23:37:41,132 - cc_refresh_rmc_and_interface.py[DEBUG]: No 'rmcctrl' in path, disabled
2023-03-28 23:37:41,132 - handlers.py[DEBUG]: finish: modules-final/config-refresh_rmc_and_interface: SUCCESS: config-refresh_rmc_and_interface ran successfully
2023-03-28 23:37:41,133 - modules.py[DEBUG]: Running module rightscale_userdata (<module 'cloudinit.config.cc_rightscale_userdata' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_rightscale_userdata.py'>) with frequency once-per-instance
2023-03-28 23:37:41,133 - handlers.py[DEBUG]: start: modules-final/config-rightscale_userdata: running config-rightscale_userdata with frequency once-per-instance
2023-03-28 23:37:41,133 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-datasource-none/sem/config_rightscale_userdata - wb: [644] 25 bytes
2023-03-28 23:37:41,133 - helpers.py[DEBUG]: Running config-rightscale_userdata using lock (<FileLock using file '/var/lib/cloud/instances/iid-datasource-none/sem/config_rightscale_userdata'>)
2023-03-28 23:37:41,133 - cc_rightscale_userdata.py[DEBUG]: Failed to get raw userdata in module rightscale_userdata
2023-03-28 23:37:41,134 - handlers.py[DEBUG]: finish: modules-final/config-rightscale_userdata: SUCCESS: config-rightscale_userdata ran successfully
2023-03-28 23:37:41,134 - modules.py[DEBUG]: Running module scripts-vendor (<module 'cloudinit.config.cc_scripts_vendor' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_scripts_vendor.py'>) with frequency once-per-instance
2023-03-28 23:37:41,134 - handlers.py[DEBUG]: start: modules-final/config-scripts-vendor: running config-scripts-vendor with frequency once-per-instance
2023-03-28 23:37:41,134 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-datasource-none/sem/config_scripts_vendor - wb: [644] 25 bytes
2023-03-28 23:37:41,134 - helpers.py[DEBUG]: Running config-scripts-vendor using lock (<FileLock using file '/var/lib/cloud/instances/iid-datasource-none/sem/config_scripts_vendor'>)
2023-03-28 23:37:41,135 - handlers.py[DEBUG]: finish: modules-final/config-scripts-vendor: SUCCESS: config-scripts-vendor ran successfully
2023-03-28 23:37:41,135 - modules.py[DEBUG]: Running module scripts-per-once (<module 'cloudinit.config.cc_scripts_per_once' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_scripts_per_once.py'>) with frequency once
2023-03-28 23:37:41,135 - handlers.py[DEBUG]: start: modules-final/config-scripts-per-once: running config-scripts-per-once with frequency once
2023-03-28 23:37:41,135 - util.py[DEBUG]: Writing to /var/lib/cloud/sem/config_scripts_per_once.once - wb: [644] 24 bytes
2023-03-28 23:37:41,136 - helpers.py[DEBUG]: Running config-scripts-per-once using lock (<FileLock using file '/var/lib/cloud/sem/config_scripts_per_once.once'>)
2023-03-28 23:37:41,136 - handlers.py[DEBUG]: finish: modules-final/config-scripts-per-once: SUCCESS: config-scripts-per-once ran successfully
2023-03-28 23:37:41,136 - modules.py[DEBUG]: Running module scripts-per-boot (<module 'cloudinit.config.cc_scripts_per_boot' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_scripts_per_boot.py'>) with frequency always
2023-03-28 23:37:41,136 - handlers.py[DEBUG]: start: modules-final/config-scripts-per-boot: running config-scripts-per-boot with frequency always
2023-03-28 23:37:41,136 - helpers.py[DEBUG]: Running config-scripts-per-boot using lock (<cloudinit.helpers.DummyLock object at 0x7fe94a161360>)
2023-03-28 23:37:41,136 - handlers.py[DEBUG]: finish: modules-final/config-scripts-per-boot: SUCCESS: config-scripts-per-boot ran successfully
2023-03-28 23:37:41,136 - modules.py[DEBUG]: Running module scripts-per-instance (<module 'cloudinit.config.cc_scripts_per_instance' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_scripts_per_instance.py'>) with frequency once-per-instance
2023-03-28 23:37:41,136 - handlers.py[DEBUG]: start: modules-final/config-scripts-per-instance: running config-scripts-per-instance with frequency once-per-instance
2023-03-28 23:37:41,137 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-datasource-none/sem/config_scripts_per_instance - wb: [644] 25 bytes
2023-03-28 23:37:41,137 - helpers.py[DEBUG]: Running config-scripts-per-instance using lock (<FileLock using file '/var/lib/cloud/instances/iid-datasource-none/sem/config_scripts_per_instance'>)
2023-03-28 23:37:41,137 - handlers.py[DEBUG]: finish: modules-final/config-scripts-per-instance: SUCCESS: config-scripts-per-instance ran successfully
2023-03-28 23:37:41,137 - modules.py[DEBUG]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_scripts_user.py'>) with frequency once-per-instance
2023-03-28 23:37:41,138 - handlers.py[DEBUG]: start: modules-final/config-scripts-user: running config-scripts-user with frequency once-per-instance
2023-03-28 23:37:41,138 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-datasource-none/sem/config_scripts_user - wb: [644] 24 bytes
2023-03-28 23:37:41,138 - helpers.py[DEBUG]: Running config-scripts-user using lock (<FileLock using file '/var/lib/cloud/instances/iid-datasource-none/sem/config_scripts_user'>)
2023-03-28 23:37:41,138 - handlers.py[DEBUG]: finish: modules-final/config-scripts-user: SUCCESS: config-scripts-user ran successfully
2023-03-28 23:37:41,138 - modules.py[DEBUG]: Running module ssh-authkey-fingerprints (<module 'cloudinit.config.cc_ssh_authkey_fingerprints' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_ssh_authkey_fingerprints.py'>) with frequency once-per-instance
2023-03-28 23:37:41,139 - handlers.py[DEBUG]: start: modules-final/config-ssh-authkey-fingerprints: running config-ssh-authkey-fingerprints with frequency once-per-instance
2023-03-28 23:37:41,139 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-datasource-none/sem/config_ssh_authkey_fingerprints - wb: [644] 25 bytes
2023-03-28 23:37:41,139 - helpers.py[DEBUG]: Running config-ssh-authkey-fingerprints using lock (<FileLock using file '/var/lib/cloud/instances/iid-datasource-none/sem/config_ssh_authkey_fingerprints'>)
2023-03-28 23:37:41,140 - util.py[DEBUG]: Reading from /etc/ssh/sshd_config (quiet=False)
2023-03-28 23:37:41,140 - util.py[DEBUG]: Read 3254 bytes from /etc/ssh/sshd_config
2023-03-28 23:37:41,141 - util.py[DEBUG]: Changing the ownership of /home/administrator/.ssh to 1000:1000
2023-03-28 23:37:41,141 - util.py[DEBUG]: Writing to /home/administrator/.ssh/authorized_keys - wb: [600] 0 bytes
2023-03-28 23:37:41,141 - util.py[DEBUG]: Changing the ownership of /home/administrator/.ssh/authorized_keys to 1000:1000
2023-03-28 23:37:41,141 - util.py[DEBUG]: Reading from /home/administrator/.ssh/authorized_keys (quiet=False)
2023-03-28 23:37:41,142 - util.py[DEBUG]: Read 0 bytes from /home/administrator/.ssh/authorized_keys
2023-03-28 23:37:41,142 - handlers.py[DEBUG]: finish: modules-final/config-ssh-authkey-fingerprints: SUCCESS: config-ssh-authkey-fingerprints ran successfully
2023-03-28 23:37:41,142 - modules.py[DEBUG]: Running module keys-to-console (<module 'cloudinit.config.cc_keys_to_console' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_keys_to_console.py'>) with frequency once-per-instance
2023-03-28 23:37:41,143 - handlers.py[DEBUG]: start: modules-final/config-keys-to-console: running config-keys-to-console with frequency once-per-instance
2023-03-28 23:37:41,143 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-datasource-none/sem/config_keys_to_console - wb: [644] 25 bytes
2023-03-28 23:37:41,143 - helpers.py[DEBUG]: Running config-keys-to-console using lock (<FileLock using file '/var/lib/cloud/instances/iid-datasource-none/sem/config_keys_to_console'>)
2023-03-28 23:37:41,143 - subp.py[DEBUG]: Running command ['/usr/lib/cloud-init/write-ssh-key-fingerprints', '', 'ssh-dss'] with allowed return codes [0] (shell=False, capture=True)
2023-03-28 23:37:41,218 - handlers.py[DEBUG]: finish: modules-final/config-keys-to-console: SUCCESS: config-keys-to-console ran successfully
2023-03-28 23:37:41,218 - modules.py[DEBUG]: Running module install-hotplug (<module 'cloudinit.config.cc_install_hotplug' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_install_hotplug.py'>) with frequency once-per-instance
2023-03-28 23:37:41,218 - handlers.py[DEBUG]: start: modules-final/config-install-hotplug: running config-install-hotplug with frequency once-per-instance
2023-03-28 23:37:41,218 - util.py[DEBUG]: Writing to /var/lib/cloud/instances/iid-datasource-none/sem/config_install_hotplug - wb: [644] 25 bytes
2023-03-28 23:37:41,219 - helpers.py[DEBUG]: Running config-install-hotplug using lock (<FileLock using file '/var/lib/cloud/instances/iid-datasource-none/sem/config_install_hotplug'>)
2023-03-28 23:37:41,219 - stages.py[DEBUG]: Allowed events: {<EventScope.NETWORK: 'network'>: {<EventType.BOOT_NEW_INSTANCE: 'boot-new-instance'>}}
2023-03-28 23:37:41,219 - stages.py[DEBUG]: Event Denied: scopes=['network'] EventType=hotplug
2023-03-28 23:37:41,219 - cc_install_hotplug.py[DEBUG]: Skipping hotplug install, not enabled
2023-03-28 23:37:41,219 - handlers.py[DEBUG]: finish: modules-final/config-install-hotplug: SUCCESS: config-install-hotplug ran successfully
2023-03-28 23:37:41,220 - modules.py[DEBUG]: Running module final-message (<module 'cloudinit.config.cc_final_message' from '/usr/lib/python3/dist-packages/cloudinit/config/cc_final_message.py'>) with frequency always
2023-03-28 23:37:41,220 - handlers.py[DEBUG]: start: modules-final/config-final-message: running config-final-message with frequency always
2023-03-28 23:37:41,220 - helpers.py[DEBUG]: Running config-final-message using lock (<cloudinit.helpers.DummyLock object at 0x7fe94a161360>)
2023-03-28 23:37:41,220 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2023-03-28 23:37:41,220 - util.py[DEBUG]: Read 14 bytes from /proc/uptime
2023-03-28 23:37:41,309 - util.py[DEBUG]: Cloud-init v. 22.4.2-0ubuntu0~22.04.1 finished at Tue, 28 Mar 2023 23:37:41 +0000. Datasource DataSourceNone.  Up 144.05 seconds
2023-03-28 23:37:41,309 - util.py[DEBUG]: Writing to /var/lib/cloud/instance/boot-finished - wb: [644] 70 bytes
2023-03-28 23:37:41,310 - cc_final_message.py[WARNING]: Used fallback datasource
2023-03-28 23:37:41,312 - handlers.py[DEBUG]: finish: modules-final/config-final-message: SUCCESS: config-final-message ran successfully
2023-03-28 23:37:41,312 - main.py[DEBUG]: Ran 12 modules with 0 failures
2023-03-28 23:37:41,312 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/status.json (via temporary file /var/lib/cloud/data/tmps33mzq2h) - w: [644] 567 bytes/chars
2023-03-28 23:37:41,313 - atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/result.json (via temporary file /var/lib/cloud/data/tmpt3hnh9d2) - w: [644] 65 bytes/chars
2023-03-28 23:37:41,313 - util.py[DEBUG]: Creating symbolic link from '/run/cloud-init/result.json' => '../../var/lib/cloud/data/result.json'
2023-03-28 23:37:41,313 - util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
2023-03-28 23:37:41,313 - util.py[DEBUG]: Read 14 bytes from /proc/uptime
2023-03-28 23:37:41,313 - util.py[DEBUG]: cloud-init mode 'modules' took 0.366 seconds (0.37)
2023-03-28 23:37:41,313 - handlers.py[DEBUG]: finish: modules-final: SUCCESS: running modules for final
